### ISSUE TITLE
Displaying SDS Label All Time

### ISSUE THREAD

**Issue by stephenplantnca** [rcpch/digital-growth-charts-react-component-library#51] opened 2023-07-20 14:48 UTC
Have a request from a clinician here.
The want the SDS label that are displayed when you hover over the SDS line in the BMI to be displayed all the time.

This is so there visible when the chart is print out and sent externally.

Is that possible?

Thanks
![BMI Chart SDS Label](https://github.com/rcpch/digital-growth-charts-react-client/assets/140090577/3728a048-fceb-4b1b-800e-6ecbac2b465a)

**Comment by eatyourpeas** [comment] 2023-07-20 18:24
Thanks @stephenplantnca - this is a duplicate of #49 so tagging here.
This is slated for future updates.

**Comment by eatyourpeas** [comment] 2024-04-01 23:08
Fixed and merged in v7.0.0. Documentation updated

**Closed as completed by eatyourpeas** 2024-04-01 23:08 UTC
Labels: duplicate, feature request
